2019-09-04@15:00 commit of my custom scripts

diff --git a/bin/git-bump b/bin/git-bump
--- a/bin/git-bump
+++ b/bin/git-bump
@@ -12,6 +12,8 @@
 # Accepts one arg: [major|minor|patch]
 #:ABOUT
 
+incr=""
+
 if [[ $# != 1 || ! -f .bumpversion.cfg ]]
 then 
     echo
@@ -23,8 +25,46 @@ then
     #echo "(Uses python package 'bumpversion')"
     #bumpversion
     echo
-    exit
+    #exit
+
+    echo "Interactive mode? [Y/n] "
+    read -t 5 answer
+    if [[ $answer =~ ^[Yy]$ || $answer =~ [yes] ]]
+    then
+
+        echo "Version amount:"
+        makemenu.sh "cancel" "patch" "minor" "major"
+        choice=$(cat /tmp/menuselect.val)
+        [ $choice = "cancel" ] && exit
+        echo "-- git bump $choice --"
+        incr=$choice
+        echo
+        echo "-----------------------------------------"
+        git status -suno
+        echo "-----------------------------------------"
+        else exit
+    fi
+else incr=$1
 fi
+
+[ $incr = "" ] && exit 1
+
+### Verify bumpversion is installed ###
+if [ ! `which bumpversion` ]
+then
+    echo "Cannot find bumpversion"
+    echo "Attempting to install..."
+
+    python3 -m pip install bumpversion
+
+    if [ `which bumpversion` ]
+    then echo "Successfully installed bumpversion" && which bumpversion
+    else echo "Failed to install bumpversion. It is required for 'git bump' to function properly."
+         exit 1
+    fi
+fi
+
+! which -s bumpversion && exit 1
 
 curver=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
 newver=$(grep current_version .bumpversion.cfg | cut -d '=' -f2 | tr -d ' ')
@@ -37,6 +77,7 @@ bumpversion --allow-dirty $1
 newver=$(grep current_version .bumpversion.cfg | cut -d '=' -f2 | tr -d ' ')
 
 echo "new bumped version: $newver"
+echo
 
 mvn versions:set -DnewVersion="$newver-SNAPSHOT"
 
